version: '3'

volumes:
  db:
    driver: local

services:
  db:
    image: mysql:5.7.29
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ONETIME_PASSWORD: null
    env_file: .env
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
      - db:/var/lib/mysql

  redis:
    image: redis:5.0.7-alpine
    ports:
      - "${REDIS_PORT}:6379"

