---
- name: Configure Git
  git_config:
    repo: "{{ project.dir }}/.git"
    scope: local
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - name: user.name
      value: "{{ git.config.user.name }}"
    - name: user.email
      value: "{{ git.config.user.email }}"

#  - name: Commit Rails project initialization
#    shell: >
#      git add .;
#      git commit -m "Init project";
#    args:
#      chdir: "{{ project.dir }}"
